"""Utility script to compute quantization ratios per patient and per method.

This script reads the clinical label sheet and augments it with the voxel
distribution (ratios) across the eight quantization labels generated by
different DSC processing methods.
"""

import argparse
import os
from functools import partial
from multiprocessing import Pool, cpu_count
from typing import Dict, Iterable, List, Optional, Sequence

import nibabel as nib
import numpy as np
import pandas as pd
from tqdm import tqdm


METHOD_FILES: Dict[str, str] = {
    "AE": "AE_quantization.nii.gz",
    "dVAE": "dVAE_quantization.nii.gz",
    "metric": "metric_quantization.nii.gz",
    "param": "param_quantization.nii.gz",
    "CE": "tumor_mask.nii.gz",
}


def compute_label_ratios(mask_path: str, labels: Sequence[int]) -> List[float]:
    """Return the voxel ratios for the requested labels within a mask image."""

    if not os.path.exists(mask_path):
        return [np.nan] * len(labels)

    mask_img = nib.load(mask_path)
    mask_data = mask_img.get_fdata()

    positive_voxels = mask_data[np.isin(mask_data, labels)]
    if positive_voxels.size == 0:
        return [np.nan] * len(labels)

    total_voxels = float(positive_voxels.size)
    ratios = [(positive_voxels == label).sum() / total_voxels for label in labels]
    return ratios


def ensure_columns(dataframe: pd.DataFrame, methods: Iterable[str], labels: Sequence[int]) -> None:
    if "phase" not in dataframe.columns:
        dataframe["phase"] = np.nan

    # Add voxel count columns for each tumor region
    tumor_regions = ["WT", "CE", "NE"]
    for region in tumor_regions:
        column = f"{region}_voxel_count"
        if column not in dataframe.columns:
            dataframe[column] = np.nan

    # Add ratio columns for each method, label, and tumor region
    for method in methods:
        for label in labels:
            for region in tumor_regions:
                column = f"{method}_{region}_ratio_{label}"
                if column not in dataframe.columns:
                    dataframe[column] = np.nan


def resolve_patient_directory(base_dir: str, patient_id: str) -> str:
    patient_dir = os.path.join(base_dir, patient_id, "dsc", "dsc_clusters")
    alt_dir = os.path.join(base_dir, patient_id, "dsc_clusters")

    if os.path.isdir(patient_dir):
        return patient_dir
    if os.path.isdir(alt_dir):
        return alt_dir
    return ""


def _process_single_patient(
    task: tuple,
    phase_roots: Sequence[tuple],
    methods: Dict[str, str],
    labels: Sequence[int],
):
    idx, patient_id = task

    cluster_dir = ""
    patient_dir = ""
    assigned_phase = ""

    for phase_name, root_path in phase_roots:
        if not root_path:
            continue
        candidate = resolve_patient_directory(root_path, patient_id)
        if candidate:
            cluster_dir = candidate
            assigned_phase = phase_name
            tentative_patient_dir = os.path.join(root_path, patient_id)
            if os.path.isdir(tentative_patient_dir):
                patient_dir = tentative_patient_dir
            else:
                patient_dir = os.path.dirname(cluster_dir)
            break

    if not cluster_dir:
        return idx, None, [], {}

    ratio_entries = []
    tumor_regions = ["WT", "CE", "NE"]
    
    for method, filename in methods.items():
        candidate_paths = [os.path.join(cluster_dir, filename)]
        if patient_dir:
            candidate_paths.append(os.path.join(patient_dir, filename))

        mask_path = ""
        for candidate_path in candidate_paths:
            if os.path.exists(candidate_path):
                mask_path = candidate_path
                break
        if not mask_path:
            mask_path = candidate_paths[0]

        # Compute ratios for each tumor region
        for region in tumor_regions:
            region_mask_path = ""
            if patient_dir:
                region_mask_candidates = [
                    os.path.join(patient_dir, f"{region}_tumor_mask.nii.gz"),
                    os.path.join(patient_dir, f"{region}_tumor_mask.nii"),
                ]
                for region_path in region_mask_candidates:
                    if os.path.exists(region_path):
                        region_mask_path = region_path
                        break
            
            if region_mask_path:
                # Apply tumor region mask to quantization mask
                region_mask_img = nib.load(region_mask_path)
                region_mask_data = region_mask_img.get_fdata()
                
                quant_img = nib.load(mask_path)
                quant_data = quant_img.get_fdata()
                
                # Apply tumor region mask to quantization data
                masked_quant_data = quant_data * region_mask_data
                
                # Save temporary masked file for ratio computation
                temp_path = f"/tmp/temp_{method}_{region}_{patient_id}.nii.gz"
                temp_img = nib.Nifti1Image(masked_quant_data, quant_img.affine, quant_img.header)
                nib.save(temp_img, temp_path)
                
                ratios = compute_label_ratios(temp_path, labels)
                
                # Clean up temporary file
                if os.path.exists(temp_path):
                    os.remove(temp_path)
                
                for label, ratio in zip(labels, ratios):
                    ratio_entries.append((method, region, label, ratio))

    # Compute voxel counts for each tumor region
    voxel_counts = {}
    if patient_dir:
        for region in tumor_regions:
            region_mask_candidates = [
                os.path.join(patient_dir, f"{region}_tumor_mask.nii.gz"),
                os.path.join(patient_dir, f"{region}_tumor_mask.nii"),
            ]
            voxel_count = np.nan
            for region_path in region_mask_candidates:
                if os.path.exists(region_path):
                    region_mask_img = nib.load(region_path)
                    region_mask_data = region_mask_img.get_fdata()
                    voxel_count = float(np.count_nonzero(region_mask_data))
                    break
            voxel_counts[region] = voxel_count

    return idx, assigned_phase, ratio_entries, voxel_counts


def process_patients(
    dataframe: pd.DataFrame,
    phase_roots: Sequence[tuple],
    methods: Dict[str, str],
    labels: Sequence[int],
    num_workers: Optional[int] = None,
) -> pd.DataFrame:
    ensure_columns(dataframe, methods.keys(), labels)

    tasks: List[tuple] = []
    for idx, row in dataframe.iterrows():
        patient_id = str(row["patient_id"]).strip().zfill(8)
        tasks.append((idx, patient_id))

    if not tasks:
        return dataframe.iloc[0:0].reset_index(drop=True)

    keep_indices: List[int] = []

    worker = partial(
        _process_single_patient,
        phase_roots=phase_roots,
        methods=methods,
        labels=labels,
    )

    effective_workers = num_workers or cpu_count()
    effective_workers = max(1, min(effective_workers, len(tasks)))

    iterator: Iterable
    pool: Optional[Pool] = None
    if effective_workers == 1:
        iterator = (
            worker(task) for task in tqdm(tasks, total=len(tasks), desc="Patients")
        )
    else:
        pool = Pool(processes=effective_workers)
        iterator = tqdm(
            pool.imap_unordered(worker, tasks, chunksize=1),
            total=len(tasks),
            desc="Patients",
        )

    try:
        for idx, assigned_phase, ratio_entries, voxel_counts in iterator:
            if assigned_phase is None:
                continue
            dataframe.at[idx, "phase"] = assigned_phase
            keep_indices.append(idx)
            
            # Set voxel counts for each tumor region
            for region, voxel_count in voxel_counts.items():
                dataframe.at[idx, f"{region}_voxel_count"] = voxel_count
            
            # Set ratios for each method, region, and label
            for method, region, label, ratio in ratio_entries:
                if region == "WT":
                    dataframe.at[idx, f"{method}_ratio_{label}"] = ratio
                else:
                    dataframe.at[idx, f"{method}_{region}_ratio_{label}"] = ratio
    finally:
        if pool is not None:
            pool.close()
            pool.join()

    return dataframe.loc[keep_indices].reset_index(drop=True)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compute quantization ratios and augment label sheet.")
    parser.add_argument(
        "--label-csv",
        required=True,
        help="Absolute path to the clinical label CSV file (patient_id, who_grade, idh, ...).",
    )
    parser.add_argument(
        "--external-label-csv",
        default=None,
        help="Optional external cohort label CSV to include for benchmarking.",
    )
    parser.add_argument(
        "--train-root",
        required=True,
        help="Directory containing training patient subdirectories with quantization masks.",
    )
    parser.add_argument(
        "--eval-root",
        required=True,
        help="Directory containing evaluation patient subdirectories with quantization masks.",
    )
    parser.add_argument(
        "--external-root",
        default=None,
        help="Optional directory containing external test patient subdirectories.",
    )
    parser.add_argument(
        "--output-csv",
        default="./label_with_quantization.csv",
        help="Path to save the augmented CSV file.",
    )
    parser.add_argument(
        "--labels",
        type=int,
        nargs="*",
        default=list(range(1, 9)),
        help="Label values to compute ratios for.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_arguments()

    df_list = [pd.read_csv(args.label_csv)]
    if args.external_label_csv and os.path.isfile(args.external_label_csv):
        df_list.append(pd.read_csv(args.external_label_csv))

    df = pd.concat(df_list, ignore_index=True)
    print(len(df))

    phase_roots = []
    if args.train_root and os.path.isdir(args.train_root):
        phase_roots.append(("train", args.train_root))
    if args.eval_root and os.path.isdir(args.eval_root):
        phase_roots.append(("test", args.eval_root))
    if args.external_root and os.path.isdir(args.external_root):
        phase_roots.append(("test_upenn", args.external_root))

    df = process_patients(df, phase_roots, METHOD_FILES, args.labels)
    df.to_csv(args.output_csv, index=False)
    print(f"Saved augmented label sheet to {args.output_csv}")


if __name__ == "__main__":
    main()


